# Data Science - Python Intro

## Installatie

Om Python en Jupyter Notebook te installeren volg je [deze link](https://www.anaconda.com/products/individual#windows).
Anaconda is een bundle met Python en een groot aantal extra packages die vaak gebruikt worden bij Data Science en Machine Learning.
Download de executable en installeer het.
Hierbij mogen de default opties gekozen worden.

Ook al heeft Anaconda zijn eigen package manager (conda), niet alle packages kunnen door deze correct gevonden worden. Daarom moet je ook nog pip installeren door middel van onderstaande commando.

Dit is bijgetypt als voorbeeld

In [1]:
!conda install pip

^C


Clone nu de github repo waar deze file in staat. Deze kan gevonden worden via [de link, pas dit aan naar de repo van dit jaar](TODO).
Open nu een commandprompt (cmd.exe) en navigeer met behulp van cd naar de folder waar je de repo geplaatst hebt.
Voer op die plaats het commando **jupyter notebook** uit.
Dit opent een webpagina met de inhoud van je folder waar je zat.
Open nu het notebook dat we hier gebruiken (Deze file noemt **PythonIntro**).

Op dit punt zou je hetzelfde moeten zien als hier staat.

## Jupyter notebook

Jupyter notebook maakt het mogelijk om hier zowel de opgave, uitleg als code te tonen en uit te voeren.
Hiervoor wordt er gebruik gemaakt van cellen.
Ook is het mogelijk om zowel code als tekstuele vragen te stellen.

Een korte intro over jupyter notebook kan je [hier](https://realpython.com/jupyter-notebook-introduction/) lezen.
In grote lijnen wordt er gewerkt met cellen. Het type van de cel bepaalt of het python-code of plain text (markdown) bevat.
Cellen worden automatisch toegevoegd na het uitvoeren van de laatste cel maar je kan ook er manueel toevoegen onder het menu-item insert of door gebruik te maken van de knoppen "a" en "b" (Hierbij moet je wel eerst uit de cell gaan door middel van Esc). Met deze laatste methode kan je op de gewenste plaats cellen gaan toevoegen.

Uitvoeren van een code cel zorgt ervoor dat de python code die in die cell staat uitgevoerd wordt. In het geval van een markdown cell wordt de tekst gerendered.
Om 1 cell uit te voeren is "shift+enter" de gemakkeljkste methode omdat dan de onderstaande cell automatisch geselecteerd wordt. Deze manier wordt ook gebruikt bij het pijltje met de tekst "Run" bovenaan.
Andere methoden kan je vinden onder het menu "Cell" waarbij je bijvoorbeeld ook van boven naar beneden alle cellen kan laten uitvoeren.
Als je ooit in een situatie zit waar je een endless loop gemaakt hebt of je code lijkt vast te zitten, kan je onder kernel een aantal manieren vinden om het uitvoeren te stoppen. 
Merk op dat als je de kernel stopt, je dan ook alle variabelen en objecten kwijt bent en je opnieuw de code vanin het begin moet uitvoeren.

**Let op:** Bij het pushen naar github van de code is het aangeraden om de output te verwijderen die je hebt gegenereerd.
Dit kan de bestandsgrootte sterk reduceren en vermijdt conflicten. 
Hierbij is het dan wel nodig om ervoor te zorgen dat je code van boven naar beneden kan uitgevoerd worden (met de knop run-all).

## Python intro

Python is een open-source programmeertaal ontwikkeld en ontworpen begin jaren 90. 
Net zoals C# is het een object-georienteerde programmeertaal waarin gebruik gemaakt wordt van klassen en objecten voor structuur aan te brengen in je code. 
Het doel van Python is om een zeer leesbare programmeertaal te zijn en code lijkt sterk op pseudocode. 
In dit vak werken we met Python versie 3.x. 
De syntax vanaf versie 3 is licht afwijkend met die van Python versie 2.x.

Het grootste verschil met C# is dat Python een scripting taal is die gebruik maakt van een interpreter in plaats van een compiler. Dit houdt in dat er geen compile/build step is. Een file of een tekst met Python code wordt door de interpreter ingelezen en lijn voor lijn uitgevoerd.

Python code kan
 * Rechtstreeks in de commandline uitgevoerd worden. Voer hiervoor het commando "python" uit. Dit start de interpreter waar er berekeningen kunnen uitgevoerd worden.
 * Je kan een file aanmaken waar dezelfde lijnen in staan. Wanneer je nu navigeert naar je directory in commandline en daar het commando "python **filename**.py" uitvoert, dan krijg je hetzelfde resultaat. Merk op dat files met python code standaard de extensie .py hebben maar dat dit niet strikt noodzakelijk is.
 * Daarnaast kan je net hetzelfde doen in een cell van jupyter notebook

In [1]:
a = 5
b = 7 

c = a+b
print(c)
# Dit is een commentaar lijn
# Dit is een andere lijn
#
#

12


De grootste verschillen met C# zijn:
* Een scripting taal dus geen compileer stap nodig (het kan wel gedaan worden voor de snelheid van het programma te verbeteren)
* Dynamisch typecasting dus moet niet steeds het type meegegeven worden bij het aanmaken van variabele, definieren van functies en klassen
* Indentation ipv van accolades voor code blocks

Nu ga ik een hele reeks zaken overlopen om de basis van python te leren kennen. 
Merk op dat in de loop van dit vak we python gaan gebruiken op een vereenvoudigde manier dus is het niet nodig om alle details te kennen van hoe python werkt.

In [64]:
# aanmaken van een floating point
a = 6.3
b = -5.2
a-b

# aanmaken van een string
a = int("5")
b = int('7')
a+b
len("dit is een lange string!")

# aanmaken van een list (meerdere types combineren kan maar is niet vaak gewenst)
lijstje = [0,1,2,3,"4",5,"6",7,True,9]
lijstje[2]
lijstje[-2]
lijstje[3:5]
#lijstje[begin:end:step]
lijstje[1:-1:2]

# aanmaken tuple
i, naam = (0, "Jens")
print(i)
print(naam)

# aanmaken dictionary
dictionary = {"0": "Naam", 1:"naam", 3:"test"}
dictionary["Jens"]="value"
print(dictionary)

# output (concatenate of multiple arguments of f-strings f'adfafd {geen string object} afdaf' )
print(i,naam,dictionary, sep=" , ")
print(f'test test {dictionary} test')

# input
#input()

# set string om naar int of omgekeerd
str(a)

# aanmaken functie (default args)
def functienaam(a= 2, b = 1):
    return a+b

functienaam(b=6)

# if-test
if a > b:
    pass
elif a < b:
    pass
else:
    pass

# for loop
#for iterator in range(20):
#    print(iterator)

# while loop
while a < b:
    break
    
# insert in lijst
#lijstje.append(20)
#lijstje.extend(range(10))
lijstje.insert(1, "a")
lijstje

# lijst concatenation

lijstje + lijstje

# classe aanmaken
class Person:
    age=0
    
    def __init__(self, name, age=0, adress="a"):
        self.naam = name
        self.age = age
        self.leeftijd = age
        self.adress = adress
        
persoon = Person("test1", 5)
persoon2 = Person("test2", 10)

print(persoon.age, persoon2.age)

# Inheritance

class Student(Person):
    
    def __init__(self, ...):

0
Jens
{'0': 'Naam', 1: 'naam', 3: 'test', 'Jens': 'value'}
0 , Jens , {'0': 'Naam', 1: 'naam', 3: 'test', 'Jens': 'value'}
test test {'0': 'Naam', 1: 'naam', 3: 'test', 'Jens': 'value'} test
5 10


### Oefening

* Maak een klasse Persoon aan, die minstens een naam en leeftijd en adres heeft.
* Maak een klasse Student aan die hiervan over erft die ook nog een dictionary bijhoudt met welke scores de student had voor welk vak. 
* Maak functies in deze klassen aan om scores toe te voegen, te tellen voor hoeveel vakken de student erdoor is en zijn gemiddelde te berekenen
* Maak een aparte functie aan die een lijst studenten als argument meekrijgt en bepaalt hoeveel studenten er door zijn.
* Maak een aparte functie aan die een lijst studenten als argument meekrijgt en bepaalt voor elk vak hoeveel studenten er door zijn.

In [4]:
# Oefening 1: Persoon

class Persoon:    
    def __init__(self, naam, leeftijd, adres):
        self.naam = naam
        self.leeftijd = leeftijd
        self.adres = adres
        
p = Persoon("John Doe", 19, "Gent")
print(p.naam, p.leeftijd, p.adres)

John Doe 19 Gent


In [20]:
# Oefening 2: Student

class Student(Persoon):
    
    def __init__(self, naam, leeftijd, adres):
        super().__init__(naam, leeftijd, adres)
        self.scores = {}
    
    # extra voor oefening 3
    def add_score(self, vak, punten):
        self.scores[vak] = punten
    
    def aantal_vakken_geslaagd(self):
        aantal = 0
        for i in self.scores:
            if self.scores[i] >=10:
                aantal = aantal + 1
                
        return aantal
    
    def bereken_gemiddelde(self):
        if len(self.scores) == 0:
            return 0
        
        gemiddelde = 0
        for i in self.scores:
            gemiddelde = gemiddelde + self.scores[i]
                
        return gemiddelde / len(self.scores)
        
s = Student("John Doe", 19, "Gent")
print(s.naam, s.leeftijd, s.adres)

# extra voor oefening 3
s.add_score("Data Science", 15)
s.add_score("Big Data", 12)
s.add_score("Machine Learning", 8)

print(s.naam, s.aantal_vakken_geslaagd())
print(s.naam, s.bereken_gemiddelde())
print(s.scores)

John Doe 19 Gent
{'Data Science': 15, 'Big Data': 12, 'Machine Learning': 8}


In [18]:
# Oefening 4: Hoeveel studenten geslaagd voor een vak
def aantal_studenten_geslaagd(studentenlijst, vak):
    aantal = 0
    for student in studentenlijst:
        if vak in student.scores:
            if student.scores[vak] >= 10:
                aantal += 1
    
    return aantal

s = Student("John Doe", 19, "Gent")
s.add_score("Data Science", 15)
s.add_score("Big Data", 12)
s.add_score("Machine Learning", 8)

studentenlijst = [s]

s = Student("Jane Doe", 20, "Leuven")
s.add_score("Data Science", 9)
s.add_score("Big Data", 5)
s.add_score("Machine Learning", 13)

studentenlijst.append(s)

s = Student("John Smith", 30, "Antwerpen")
s.add_score("Data Science", 19)
s.add_score("Big Data", 15)
s.add_score("Machine Learning", 0)

studentenlijst.append(s)

aantal_studenten_geslaagd(studentenlijst, "Data Science")

2

In [19]:
# Oefening 5: Hoeveel studenten geslaagd voor elk vak
def aantal_geslaagd_per_vak(studentenlijst):
    vakken = {}
    
    # zoek alle vakken
    for student in studentenlijst:
        for vak in student.scores:
            if vak not in vakken:
                vakken[vak] = 0
                
    for vak in vakken:
        vakken[vak] = aantal_studenten_geslaagd(studentenlijst, vak)
        
    return vakken

aantal_geslaagd_per_vak(studentenlijst)
    

{'Data Science': 2, 'Big Data': 2, 'Machine Learning': 1}

## Numpy Intro

De numpy libary of package is de kern van veel andere wiskundige rekentools for datamanagement of machine learning in python.
Het biedt onder andere een hoge performantie om te werken met rijen van meerdere dimensies en een reeks tools voor bewerkingen te doen met en op deze rijen.
* Een 1-dimensionale rij is een een normale rij
* Een 2-dimensionale rij is een matrix
* Een 3-dimensionale rij is bijvoorbeeld een RGB-figuur (derde dimensie bestaat uit drie elementen)

De standaard manier om deze package te gebruiken is door bovenaan je file de package te importeren met het commando:

In [2]:
import numpy as np

In [3]:
# Aanmaken arrays
np.array([0, 1, 2, 3, 4])
np.array([[0, 1, 2], [3, 4,5]])
np.ones((10,5))
np.zeros((10,5))
np.eye(10)

# Bestuderen van de matrices
m = np.arange(10).reshape((5,2))
m[1::2]
print(m)

# Bewerkingen met arrays
print(m+m)
print(m*m)
m**2
m-0.5*m

# Vergelijken van rijen
m[m > 5]

# Aggregate functies
np.sum(m)
np.mean(m)
np.median(m)

# Copy arrays
m2 = m
print(m)
m2[0,0]=-1
print(m, m2)

m.copy()

# Sort
np.random.random((10,5))
rnd = np.random.randint(10, size=(10,5))
print(rnd)
np.sort(rnd, axis=0)

# Indexing

# Dimensies array manipuleren


[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[[ 0  2]
 [ 4  6]
 [ 8 10]
 [12 14]
 [16 18]]
[[ 0  1]
 [ 4  9]
 [16 25]
 [36 49]
 [64 81]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[[-1  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]] [[-1  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]]
[[1 3 6 3 0]
 [7 3 4 2 8]
 [1 9 0 6 9]
 [5 8 4 5 0]
 [4 1 1 7 4]
 [8 1 6 0 9]
 [3 7 3 8 2]
 [5 9 6 5 4]
 [0 3 8 5 8]
 [0 7 5 7 5]]


array([[0, 1, 0, 0, 0],
       [0, 1, 1, 2, 0],
       [1, 3, 3, 3, 2],
       [1, 3, 4, 5, 4],
       [3, 3, 4, 5, 4],
       [4, 7, 5, 5, 5],
       [5, 7, 6, 6, 8],
       [5, 8, 6, 7, 8],
       [7, 9, 6, 7, 9],
       [8, 9, 8, 8, 9]])

Maak nu de volgende oefeningen voor Numpy
* Maak 2 vierkante matrices met random waarden tussen 0 en 10. De ene is een 10x5 matrix, de andere is 5x10.
* Schrijf een functie die controleert of de dimensies van de matrices voldoen aan de voorwaarden voor matrixVermenigvuldiging
* Bereken de vermenigvuldiging van de matrix
* Toon de resultaten op alle even rijen
* Bereken de som van elke kolom
* Bereken het gemiddelde van de matrix
* Verander het type van de matrix naar een integer-type
* Toon alle rijen waar de 4e kolom een even getal bevat
* Wijzig de vorm van de matrix van een 10x10 naar een 5x20
* Bereken de getransponeerde matrix
* Bereken de vierkantswortel van elk element in deze matrix