## Oefeningen Python - Numpy

## Gok het correcte getal

Maak een klasse voor een spel waarbij je een willekeurig getal moet gokken.
Deze klasse moet de volgende zaken doen:
* Een willekeurig getal tussen 0 en 20 genereren
* Een "start" functie hebben om het spel te starten
* In deze functie moet er herhaaldelijk om input gevraagd worden aan de gebruiker.
* De input moet vergeleken worden met het random getal. Als je input:
    * kleiner is dan het willekeurig getal, print je "Te laag"
    * groter is dan het willekeurig getal, print je "Te hoog"
    * gelijk is aan het getal, eindig je en print je dat je bent gewonnen
    * Gelijk is aan "Exit", eindig je en print je dat je verloren bent.
* Om te eindigen print je nog de volgende statistieken:
    * Hoeveel keer dat je gegokt hebt
    * Hoeveel je er gemiddeld naast zat
    
Vergeet zeker niet om de code te voorzien om het spel te starten

In [1]:
# tips voor met notebooks 

# cell toevoegen met de knoptjes of je kan dat doen met a of b (above of below)
# cellen verwijderen doe je met x (ctrl + x)
# verwijderde cell plakken doe je met v (ctrl + v)

# code uitvoeren: shift + enter

In [4]:
import random

class HigherLower():

    # constructor
    def __init__(self):
        self.to_guess = random.randint(0, 20)   # willekeurig getalletje in [0, 20]
        pass # dit moet er enkel staan als het de enige lijn is, anders mag het weg

    def start(self):
        # self == this uit c#

        done = False
        num_guesses = 0
        total_error = 0

        while not done:
            prompt = input("Geef een gok voor het willekeurige getal")
            if prompt == "Exit" or prompt == "exit":
                print("Je bent verloren")
                break
            
            # de try catch van c# is try except
            try:
                guess = int(prompt)
                num_guesses += 1
                total_error += abs(self.to_guess - guess)

                if guess == self.to_guess:
                    print("Je bent gewonnen")
                    done = True
                elif guess > self.to_guess:
                    print("Te hoog")
                else:
                    print("Te laag")
            except:
                print("Geen geldig getal")
                
            pass
    
        print("Aantal gokken", num_guesses)
        print("Gemiddelde fout", total_error / num_guesses)

# een object aanmaken van HigherLower
game = HigherLower()
game.start()

Te laag
Te laag
Te laag
Te laag
Te laag
Je bent gewonnen
Aantal gokken 6
Gemiddelde fout 3.5


## Matrix bewerkingen

Maak functie voor het aanmaken een matrix waar elk waarde het product is van zijn rij en kolom index (bvb op rij 4 en kolom 5 moet er 20 staan). Deze functie moet als argument het aantal rij en aantal kolommen hebben.

Maak met behulp van deze functie een matrix "a" van 5 rijen en 7 kolommen aan.

In [ ]:
# als je error krijgt die lijkt op: import numpy not found
!pip install numpy  # dit installeert numpy (je moet dit maar 1 keer doen)
# het uitroepingsteken is om het uit te voeren in de cli en niet als python code

# deze mag je ook installeren
!pip install pandas
!pip install opendatasets

In [6]:
import numpy as np  # np is de standaardafkorting

def make_matrix(num_rows, num_cols):
    matrix = np.zeros((num_rows, num_cols))
    for i in range(num_rows):
        for j in range(num_cols):
            matrix[i,j] = i * j
    return matrix

a = make_matrix(5, 7)
print(a)

[[ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  1.  2.  3.  4.  5.  6.]
 [ 0.  2.  4.  6.  8. 10. 12.]
 [ 0.  3.  6.  9. 12. 15. 18.]
 [ 0.  4.  8. 12. 16. 20. 24.]]


Maak een functie die met behulp van slicing de volgorde van de elementen in matrix "a" omdraait.

In [7]:
a[::-1, ::-1] # min:max:step , -1 is achterwaarts

array([[24., 20., 16., 12.,  8.,  4.,  0.],
       [18., 15., 12.,  9.,  6.,  3.,  0.],
       [12., 10.,  8.,  6.,  4.,  2.,  0.],
       [ 6.,  5.,  4.,  3.,  2.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.]])

Bereken de mean, median en standard deviation van elke kolom in matrix  "a".

In [11]:
a.mean() # gemiddelde van alle elementen
print(a.mean(axis=0))
print(np.median(a, axis=0))
print(a.std(axis=0))

[ 0.  2.  4.  6.  8. 10. 12.]
[ 0.  2.  4.  6.  8. 10. 12.]
[0.         1.41421356 2.82842712 4.24264069 5.65685425 7.07106781
 8.48528137]


Bereken hoeveel elementen in matrix "a" groter zijn dan 20

In [12]:
a > 20

array([[False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False],
       [False, False, False, False, False, False,  True]])

In [13]:
a[a>20]

array([24.])